In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\majain\Desktop\DataScience\DataScience by Madhur\Projects\absolute data\Case Study 1\Training Data - Classification of Patients with Abnormal Blood Pressure (N=2000)_27-Jul-2016.csv")

In [3]:
df.head()

Patient_Number  Blood_Pressure_Abnormality  Level_of_Hemoglobin  \
0               1                           1                11.28   
1               2                           0                 9.75   
2               3                           1                10.79   
3               4                           0                11.00   
4               5                           1                14.17   

   Genetic_Pedigree_Coefficient  Age  BMI  Sex  Pregnancy  Smoking  \
0                          0.90   34   23    1        1.0        0   
1                          0.23   54   33    1        NaN        0   
2                          0.91   70   49    0        NaN        0   
3                          0.43   71   50    0        NaN        0   
4                          0.83   52   19    0        NaN        0   

   Physical_activity  salt_content_in_the_diet  alcohol_consumption_per_day  \
0              45961                     48071                          NaN   
1              26106                     25333                        205.0   
2               9995                     29465                         67.0   
3              10635                      7439                        242.0   
4              15619                     49644                        397.0   

   Level_of_Stress  Chronic_kidney_disease  Adrenal_and_thyroid_disorders  
0                2                       1                              1  
1                3                       0                              0  
2                2                       1                              0  
3                1                       1                              0  
4                2                       0                              0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 15 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   Patient_Number                 2000 non-null   int64  
 1   Blood_Pressure_Abnormality     2000 non-null   int64  
 2   Level_of_Hemoglobin            2000 non-null   float64
 3   Genetic_Pedigree_Coefficient   1908 non-null   float64
 4   Age                            2000 non-null   int64  
 5   BMI                            2000 non-null   int64  
 6   Sex                            2000 non-null   int64  
 7   Pregnancy                      442 non-null    float64
 8   Smoking                        2000 non-null   int64  
 9   Physical_activity              2000 non-null   int64  
 10  salt_content_in_the_diet       2000 non-null   int64  
 11  alcohol_consumption_per_day    1758 non-null   float64
 12  Level_of_Stress                2000 non-null   i

In [5]:
#import seaborn as sns

In [6]:
df['Genetic_Pedigree_Coefficient'].mean()

0.4948165618448649

In [7]:
#import seaborn as sns

In [8]:
df['Genetic_Pedigree_Coefficient'].fillna(value = df['Genetic_Pedigree_Coefficient'].mean(), inplace = True)

In [9]:
df['Pregnancy'].value_counts()

0.0    243
1.0    199
Name: Pregnancy, dtype: int64

In [10]:
df.groupby(['Pregnancy','Blood_Pressure_Abnormality'])['Blood_Pressure_Abnormality'].count()

Pregnancy  Blood_Pressure_Abnormality
0.0        0                             113
           1                             130
1.0        0                              96
           1                             103
Name: Blood_Pressure_Abnormality, dtype: int64

In [11]:
df.drop('Pregnancy',axis = 1 , inplace = True)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 14 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   Patient_Number                 2000 non-null   int64  
 1   Blood_Pressure_Abnormality     2000 non-null   int64  
 2   Level_of_Hemoglobin            2000 non-null   float64
 3   Genetic_Pedigree_Coefficient   2000 non-null   float64
 4   Age                            2000 non-null   int64  
 5   BMI                            2000 non-null   int64  
 6   Sex                            2000 non-null   int64  
 7   Smoking                        2000 non-null   int64  
 8   Physical_activity              2000 non-null   int64  
 9   salt_content_in_the_diet       2000 non-null   int64  
 10  alcohol_consumption_per_day    1758 non-null   float64
 11  Level_of_Stress                2000 non-null   int64  
 12  Chronic_kidney_disease         2000 non-null   i

In [13]:
df['alcohol_consumption_per_day'].describe()

count    1758.000000
mean      251.008532
std       143.651884
min         0.000000
25%       126.250000
50%       250.000000
75%       377.750000
max       499.000000
Name: alcohol_consumption_per_day, dtype: float64

In [14]:
df['Level_of_Stress'].value_counts()

3    691
1    666
2    643
Name: Level_of_Stress, dtype: int64

In [15]:
def fill_alcohol_consumption(col):
    stress = col[0]
    alcohol = col[1]

    if pd.isnull(alcohol):
        if stress == 1:
            return 246
        elif stress == 2:
            return 255
        else:
            return 251
    else:
        return alcohol
    

In [16]:
df['alcohol_consumption_per_day'] = df[['Level_of_Stress','alcohol_consumption_per_day']].apply(fill_alcohol_consumption, axis = 1)

In [17]:
x = df.drop('Blood_Pressure_Abnormality', axis = 1)
y = df['Blood_Pressure_Abnormality']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [18]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

In [ ]:
param_grid = {'C': [0.1,1, 10], 
              'gamma': [1,0.1], 
              'kernel': ['linear','rbf']} 

grid = GridSearchCV(SVC(),param_grid,refit=True, cv = 3)
grid.fit(X_train,y_train)

In [ ]:
prediction = grid.predict(X_test)
print(confusion_matrix(y_test,prediction))
print(classification_report(y_test,prediction))

In [22]:
from sklearn.metrics import classification_report , confusion_matrix

In [23]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)
pred = model.predict(X_test)
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))

[[187 169]
 [124 180]]
              precision    recall  f1-score   support

           0       0.60      0.53      0.56       356
           1       0.52      0.59      0.55       304

    accuracy                           0.56       660
   macro avg       0.56      0.56      0.56       660
weighted avg       0.56      0.56      0.56       660



C:\Users\majain\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [25]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier(criterion='entropy', max_depth= 3)
model.fit(X_train, y_train)
pred = model.predict(X_test)
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))

[[325  31]
 [104 200]]
              precision    recall  f1-score   support

           0       0.76      0.91      0.83       356
           1       0.87      0.66      0.75       304

    accuracy                           0.80       660
   macro avg       0.81      0.79      0.79       660
weighted avg       0.81      0.80      0.79       660



In [27]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
model.fit(X_train, y_train)
pred = model.predict(X_test)
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))

[[309  47]
 [ 28 276]]
              precision    recall  f1-score   support

           0       0.92      0.87      0.89       356
           1       0.85      0.91      0.88       304

    accuracy                           0.89       660
   macro avg       0.89      0.89      0.89       660
weighted avg       0.89      0.89      0.89       660

