## Loan Prediction problem

Here we are trying to predict whether a person will repay the loan amount or not based on multiple parameters.


In [1]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [2]:
df = pd.read_csv(r'C:\Users\Madhur\Desktop\ensemble\Ensemble_learning-master\train_clean_data.csv',index_col=0)
df.head()

Loan_ID Dependents  ApplicantIncome  CoapplicantIncome  LoanAmount  \
1  LP001003          1             4583             1508.0       128.0   
2  LP001005          0             3000                0.0        66.0   
3  LP001006          0             2583             2358.0       120.0   
4  LP001008          0             6000                0.0       141.0   
5  LP001011          2             5417             4196.0       267.0   

   Loan_Amount_Term  Credit_History  gender_Male  married_Yes  \
1             360.0             1.0            1            1   
2             360.0             1.0            1            1   
3             360.0             1.0            1            1   
4             360.0             1.0            1            0   
5             360.0             1.0            1            1   

   education_Not Graduate  property_area_Semiurban  property_area_Urban  \
1                       0                        0                    0   
2                       0                        0                    1   
3                       1                        0                    1   
4                       0                        0                    1   
5                       0                        0                    1   

   self_employed_Yes  Loan_status_Y  
1                  0              0  
2                  1              1  
3                  0              1  
4                  0              1  
5                  1              1

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 517 entries, 1 to 613
Data columns (total 14 columns):
Loan_ID                    517 non-null object
Dependents                 517 non-null object
ApplicantIncome            517 non-null int64
CoapplicantIncome          517 non-null float64
LoanAmount                 517 non-null float64
Loan_Amount_Term           517 non-null float64
Credit_History             517 non-null float64
gender_Male                517 non-null int64
married_Yes                517 non-null int64
education_Not Graduate     517 non-null int64
property_area_Semiurban    517 non-null int64
property_area_Urban        517 non-null int64
self_employed_Yes          517 non-null int64
Loan_status_Y              517 non-null int64
dtypes: float64(4), int64(8), object(2)
memory usage: 60.6+ KB


## Train test Split

In [4]:
X = df.drop(['Loan_ID','Dependents','Loan_status_Y'],axis =1 )
y = df['Loan_status_Y']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

## Averaging the results

In [7]:
model1 = DecisionTreeClassifier()
model2 = KNeighborsClassifier()
model3 = LogisticRegression()

In [8]:
model1.fit(X_train, y_train)
model2.fit(X_train, y_train)
model3.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [10]:
pred1 = model1.predict_proba(X_test)
pred2 = model2.predict_proba(X_test)
pred3 = model3.predict_proba(X_test)

In [15]:
pred3

array([[0.20974736, 0.79025264],
       [0.4342028 , 0.5657972 ],
       [0.10744051, 0.89255949],
       [0.11889271, 0.88110729],
       [0.28713481, 0.71286519],
       [0.16579921, 0.83420079],
       [0.20319836, 0.79680164],
       [0.33262793, 0.66737207],
       [0.36335789, 0.63664211],
       [0.13950984, 0.86049016],
       [0.40858971, 0.59141029],
       [0.20429008, 0.79570992],
       [0.3417356 , 0.6582644 ],
       [0.20136413, 0.79863587],
       [0.20913757, 0.79086243],
       [0.24589125, 0.75410875],
       [0.10218374, 0.89781626],
       [0.13573648, 0.86426352],
       [0.77271537, 0.22728463],
       [0.27556434, 0.72443566],
       [0.12411157, 0.87588843],
       [0.30021964, 0.69978036],
       [0.16282817, 0.83717183],
       [0.81549191, 0.18450809],
       [0.32530077, 0.67469923],
       [0.22088499, 0.77911501],
       [0.2902337 , 0.7097663 ],
       [0.23770894, 0.76229106],
       [0.94260736, 0.05739264],
       [0.22258518, 0.77741482],
       [0.

In [11]:
final_pred = (pred1 + pred2 + pred3)/3

In [12]:
final_pred

array([[0.20324912, 0.79675088],
       [0.21140093, 0.78859907],
       [0.0358135 , 0.9641865 ],
       [0.17296424, 0.82703576],
       [0.56237827, 0.43762173],
       [0.12193307, 0.87806693],
       [0.13439945, 0.86560055],
       [0.11087598, 0.88912402],
       [0.1211193 , 0.8788807 ],
       [0.24650328, 0.75349672],
       [0.6695299 , 0.3304701 ],
       [0.40143003, 0.59856997],
       [0.2472452 , 0.7527548 ],
       [0.06712138, 0.93287862],
       [0.26971252, 0.73028748],
       [0.14863042, 0.85136958],
       [0.10072791, 0.89927209],
       [0.17857883, 0.82142117],
       [0.85757179, 0.14242821],
       [0.15852145, 0.84147855],
       [0.17470386, 0.82529614],
       [0.63340655, 0.36659345],
       [0.18760939, 0.81239061],
       [0.40516397, 0.59483603],
       [0.10843359, 0.89156641],
       [0.67362833, 0.32637167],
       [0.2300779 , 0.7699221 ],
       [0.21256965, 0.78743035],
       [0.44753579, 0.55246421],
       [0.47419506, 0.52580494],
       [0.

## Voting Classifier

We are taking the outputs of multiple classifiers like:
    1. Logistic Regression
    2. Random Forest 
    3. Gausian Naive Bayes
   
Then take the majority votes to decide the final classification.

In [16]:
clf1 = LogisticRegression()
clf2 = RandomForestClassifier()
clf3 = GaussianNB()

In [18]:
eclf1 = VotingClassifier(estimators=[('lr', clf1), ('rf', clf2), ('gnb', clf3)],weights=[1,2,4],voting='soft')
eclf1 = eclf1.fit(X_train, y_train)
prediction = eclf1.predict(X_test)


from sklearn.metrics import classification_report , confusion_matrix

print(classification_report(y_test,prediction))
print(confusion_matrix(y_test,prediction))

             precision    recall  f1-score   support

          0       0.81      0.41      0.55        41
          1       0.84      0.97      0.90       130

avg / total       0.83      0.84      0.82       171

[[ 17  24]
 [  4 126]]


C:\Users\J554696\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [12]:
eclf2 = VotingClassifier(estimators=[('lr', clf1), ('rf', clf2), ('gnb', clf3)], voting='soft')
eclf2 = eclf2.fit(X_train, y_train)
predict = eclf2.predict(X_test)
print(classification_report(y_test, predict))
print('\n')
print(confusion_matrix(y_test, predict))

             precision    recall  f1-score   support

          0       0.82      0.44      0.57        41
          1       0.85      0.97      0.90       130

avg / total       0.84      0.84      0.82       171



[[ 18  23]
 [  4 126]]


C:\Users\Madhur\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:171: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
